project:
  type: website

website:
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Se ha añadido la página [Estadística (II)](/contents/estadistica2.qmd)."
    type: info
    position: below-navbar
  title: "CálculoGATE"
  favicon: "/favicon.ico"
  page-footer:  
    center: "Esta web pertenece a [Naïm Saadi](https://nsaadig16.github.io) y es de uso **exclusivo** de los alumnos y alumnas de la academia Gauss."
    border: true
  navbar:
    logo: "/favicon.ico"
    pinned: true
    left:
      - href: contents/analisis.qmd
        text: Análisis de funciones
      - href: contents/optimizacion.qmd
        text: Optimización
      - href: contents/puntos_criticos.qmd
        text: Puntos críticos
      - href: contents/aproximacion_integrales.qmd
        text: Aproximación de integrales
      - href: contents/estadistica.qmd
        text: Estadística (I)
      - href: contents/estadistica2.qmd
        text: Estadística (II)
format:
  html:
    theme:
      - solar
    css: styles.css
    toc: true



